name: Chai HTTP

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16 # to be removed after 2023-09
          - 18
          - x.x.x # safety net; don't remove
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm test
      - uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}


  publish-npm:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}} # ff9b......76c4
          GITHUB_TOKEN: ${{secrets.GH_RELEASE_TOKEN}}
